site_name: anime
nav:
  - 一. 介绍: index.md
  - 二. 一人之下: 
      - 1. yiren: yiren001.md
      - 2. yiren: yiren002.md
      - 3. yiren: yiren003.md
      - 4. yiren: yiren004.md
      - 5. yiren: yiren005.md
      - 6. yiren: yiren006.md
      - 7. yiren: yiren007.md
      - 8. yiren: yiren008.md
      - 9. yiren: yiren009.md
      - 10. yiren: yiren010.md
      - 11. yiren: yiren011.md
      - 12. yiren: yiren012.md
      - 13. yiren: yiren013.md
      - 14. yiren: yiren014.md
      - 15. yiren: yiren015.md
      - 16. yiren: yiren016.md
      - 17. yiren: yiren017.md
      - 18. yiren: yiren018.md
      - 19. yiren: yiren019.md
      - 20. yiren: yiren020.md
      - 21. yiren: yiren021.md
      - 22. yiren: yiren022.md
      - 23. yiren: yiren023.md
      - 24. yiren: yiren024.md
      - 25. yiren: yiren025.md
      - 26. yiren: yiren026.md
      - 27. yiren: yiren027.md
      - 28. yiren: yiren028.md
      - 29. yiren: yiren029.md
      - 30. yiren: yiren030.md
      - 31. yiren: yiren031.md
      - 32. yiren: yiren032.md
      - 33. yiren: yiren033.md
      - 34. yiren: yiren034.md
      - 35. yiren: yiren035.md
      - 36. yiren: yiren036.md
      - 37. yiren: yiren037.md
      - 38. yiren: yiren038.md
      - 39. yiren: yiren039.md
      - 40. yiren: yiren040.md
  - 三. 旅游: Labor Day Travel.md

theme:
  name: 'material'
  font: 
    text: 'Consolas'
    code: 'Consolas Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
