site_name: anime
nav:
  - 一. 介绍: index.md
  - 二. 姚尧形态学: 
      - 前言: 姚尧形态学/前言.md
      - 第1集：解构: 姚尧形态学/第1集：解构.md
      - 第2集：止损: 姚尧形态学/第2集：止损.md
theme:
  name: 'material'
  font: 
    text: 'Consolas'
    code: 'Consolas Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
